# Site settings
title: Islamic Cultural Centre
email: icccetvm@gmail.com
description: "Welcome to Islamic Centre, CET "

# Color settings (hex-codes without the leading hash-tag)
color:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Postal address (add as many lines as necessary)
address:

# Build settings
markdown: kramdown
permalink: pretty
